language: android
dist: trusty
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - build-tools-29.0.1
    - android-28
    - android-29
script:
  - ./gradlew build
