language: android
dist: trusty
before_install:
    - yes | sdkmanager "platforms;android-28"
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - android-28
    - sys-img-x86_64-google_apis_playstore-28
    - sys-img-x86_64-android-28
script:
  - android list target
  - ./gradlew connectedAndroidTest
